---
title: "Distribution maps Unionidae"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE}
# Set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(root.dir = here())

# Conflicting packages
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)
conflicted::conflicts_prefer(dplyr::lag)

# Packages
library(tidyverse)
library(sf)
library(readxl)

# Source
source(here("source", "read_excel_allsheets.R"))
```

# Read in data
## Map layers

We read in different map layers to create distribution maps.

```{r, results='hide'}
proj_crs <- 32631

# Read in map layers
belgium_sf <- st_read(here("data", "maps", "Belgie.shp")) %>%
  st_transform(proj_crs)
utm5_total_sf <- st_read(here("data", "maps", "utm5.shp")) %>%
  st_transform(proj_crs)
utm10_total_sf <- st_read(here("data", "maps", "utm10.shp")) %>%
  st_transform(proj_crs)
rivieren_sf <- st_read(here("data", "maps", "hoofdrivierenbel.shp")) %>%
  st_transform(proj_crs)
kanalen_sf <- st_read(here("data", "maps", "Kanalen.shp")) %>%
  st_transform(proj_crs)
```

```{r}
# Select UTM grids that overlap with Belgium
umt5_tags <- utm5_total_sf %>%
  st_intersection(belgium_sf) %>%
  pull(TAG)

utm5_sf <- utm5_total_sf %>%
  filter(TAG %in% umt5_tags)

umt10_tags <- utm10_total_sf %>%
  st_intersection(belgium_sf) %>%
  pull(TAG)

utm10_sf <- utm10_total_sf %>%
  filter(TAG %in% umt10_tags)

# Combine water ways Belgium
waterlopen_sf <- bind_rows(
  rivieren_sf %>%
    select("naam" = NAAM) %>%
    mutate(waterloop = "rivier"),
  kanalen_sf %>%
    select("naam" = NAAM) %>%
    mutate(waterloop = "kanaal"))
```

We visualise the layers.

```{r}
ggplot() +
  geom_sf(data = belgium_sf, fill = "white",
          linewidth = 0.8) +
  geom_sf(data = waterlopen_sf, aes(colour = waterloop)) +
  geom_sf(data = utm5_sf, fill = alpha("white", 0),
          linewidth = 0.6) +
  labs(title = "UTM 5 km", x = "", y = "", colour = "Waterloop") +
  coord_sf(datum = proj_crs) +
  theme_void() +
  theme(legend.position = c(0.2, 0.2))

ggplot() +
  geom_sf(data = belgium_sf, fill = "white",
          linewidth = 0.8) +
  geom_sf(data = waterlopen_sf, aes(colour = waterloop)) +
  geom_sf(data = utm10_sf, fill = alpha("white", 0),
          linewidth = 0.6) +
  labs(title = "UTM 10 km", x = "", y = "", colour = "Waterloop") +
  coord_sf(datum = proj_crs) +
  theme_void() +
  theme(legend.position = c(0.2, 0.2))
```

## Occurrence data

We read in and prepare the data from after 1995.
Taxonomic information was added manually.

```{r}
# Read in data post 1995
data_succinea_raw <- read_excel_allsheets(
  here("data", "raw",
       "AA-Locaties-Najaden-2023-10-25-vanaf1995-Final.xlsx")
  )

# Get species list
species_list <- lapply(names(data_succinea_raw), function(sheet) {
  data_succinea_raw[[sheet]][1,] %>%
    select(Genus, Species, Author) %>%
    mutate(name = sheet)
})
species_df <- do.call(rbind.data.frame, species_list)

# Prepare data post 1995
data_succinea <- lapply(names(data_succinea_raw), function(sheet) {
  data_succinea_raw[[sheet]] %>%
    select(Locality:Alive, -c(`Lat., Long.`, "Date")) %>%
    mutate(name = sheet) %>%
    rename_with(~tolower(gsub("-", "_", .x))) %>%
    rename_with(~gsub( " .*$", "", .x))
})

data_post_1995 <- do.call(rbind.data.frame, data_succinea) %>%
  full_join(species_df, by = join_by(name)) %>%
  select(-name) %>%
  rename_with(tolower) %>%
  pivot_longer(cols = c("empty", "alive"),
               names_to = "state",
               values_to = "number") %>%
  drop_na(number) %>%
  rowid_to_column(var = "id") %>%
  mutate(period = "post_1995",
         id = paste(id, period, sep = "_"))

glimpse(data_post_1995)
```

We read in and prepare the data from before 1995.

```{r}
# Read in data pre 1995
data_nijs_raw <- read_excel_allsheets(
  here("data", "raw",
       "Alfa-Unionidae 6 soorten-Verspreiding-Nijs-1995-Empty-Alive.xlsx")
)

# Prepare data pre 1995
data_nijs <- lapply(names(data_nijs_raw), function(sheet) {
  data_nijs_raw[[sheet]] %>%
    mutate(name = sheet) %>%
    rename("empty" = `Empty t/m 1994`, "alive" = `Alive t/m 1994`)
})

data_pre_1995 <- do.call(rbind.data.frame, data_nijs) %>%
  full_join(species_df, by = join_by(name)) %>%
  select(-name) %>%
  rename_with(tolower) %>%
  pivot_longer(cols = c("empty", "alive"),
               names_to = "state",
               values_to = "utm_10km") %>%
  rowid_to_column(var = "id") %>%
  mutate(period = "pre_1995",
         id = paste(id, period, sep = "_"))

glimpse(data_pre_1995)
```
